blog/urls.py
from django.urls import path
from . import views


app_name="blog"

urlpatterns = [
    #path('', include('blog.urls')),
    path('', views.home, name="home"),
    #path('register/', views.register, name="register")
    path('signup/', views.signup, name="signup"),
    path('login_page/', views.login_page, name="login_page"),
    path('logout_page/', views.logout_page, name="logout_page"),
    path('<int:id>/user_page/', views.user_page, name="user_page"),
    path('list_of_users/', views.list_of_users, name="list_of_users"),
    path('follow_user/(?P<username>\w+)', views.follow_user, name="follow_user"),
    path('<int:id>/following/', views.following, name="following"),
    path('(?P<post_pk>[0-9]+)/', views.post_detail, name="post_detail"),
    path('write_post/', views.write_post, name="write_post"),
    path('newsfeed/', views.newsfeed, name="newsfeed"),
    path('user_posts/', views.user_posts, name="user_posts"),
    path('comment/(?P<post_pk>[0-9]+)/', views.comment, name="comment"),
    path('delete_post/(?P<post_pk>[0-9]+)/',views.delete_post, name="delete_post"),
    path('unfollow/(?P<username>\w+)', views.unfollow, name="unfollow"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('password/', views.change_password, name="password"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

app_name="blog"

urlpatterns = [
    path('blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name = 'profile')
    first_name = models.CharField(max_length = 40, null="True", default="")
    last_name = models.CharField(max_length = 40, null="True", default="")
    following = models.ManyToManyField(User, related_name="following")
    dob = models.DateField(default = datetime.date.today)
    #gender_choice = (('M',"Male"),('F',"Female"),('O',"Other"))
    #gender = models.CharField(max_length=1,choices=gender_choice,default=None)
    def __str__(self):
        # __str__ overrides the default names of the objects of this class
        # Overriding it gives a more human friendly name of the objects of this class.
        return self.user.username

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date_published = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=40)
    text = models.TextField(max_length=500)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date_published']

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField(max_length=250)
    date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    #If related_name is not used, django automatically uses the name of the model
    # with the suffix _set
    #So using related_name makes further syantax bit cleaner and less clunky.

    def __str__(self):
        return self.comment

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    #email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
    #        'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
    #    user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
            return user


#class ProfileForm(forms.Form):
#    first_name=forms.CharField(label='First Name', max_length=30)
#    last_name=forms.CharField(label='Last Name',max_length=30)
#    dob=forms.DateField(label='Date Of Birth',widget=forms.SelectDateWidget(years=[y for y in range(1930,2005)]))
#    username= forms.CharField(label='Enter Username' , min_length=4 , max_length = 50)
#    #email = forms.EmailField(label= 'Enter your email id')


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields= (
            'first_name',
            'last_name',
            'password',
        )

        

blog/views.py
from __future__ import unicode_literals


from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseForbidden
from .models import Profile , Post, Comment
from . import models
from .forms import SignUpForm, EditProfileForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .post_records import keep_record
from django.contrib.auth import update_session_auth_hash

import datetime


def home(request):
    return render(request, 'blog/home.html')


def signup(request):
     if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:login_page')
     else:
         form = SignUpForm()
     return render(request, 'blog/signup.html', {'form': form})

#Method of html forms

#def signup(request):
#
#     if request.method == 'GET':
#        return render(request, 'blog/signup.html')
#
#     elif request.method == 'POST':
#        first_name = request.POST['first_name']
#        last_name = request.POST['last_name']
#        username = request.POST['username']
#        email = request.POST['email']
#        password = request.POST['password']
#        password_again = request.POST['password_again']


#        if first_name.isalpha() and last_name.isalpha() and username.isalnum():
#            if password == password_again:
#                user = User(username = username, email = email, first_name = first_name, last_name = last_name)
#                user.set_password(password)
#                user.save()
#                profile = Profile(user=user)
#                profile.save()
#
#                return render(request, 'blog/login_page.html')
#
#            else:
#                messages.error(request, "Your passwords don't match!")
#                return redirect('blog:signup')
#
#        else:
#            messages.error(request, "Please fill all the fields!")
#            return redirect('blog:signup')



def login_page(request):
    if request.method == 'GET':
        return render(request, 'blog/login_page.html')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)


        if user is not None:
            django_login(request, user)
            return redirect('blog:user_page',user.id)

        else:
            messages.error(request, "Entered Username/Password does not match.")
            return redirect('blog:login_page')


def logout_page(request):
    django_logout(request)
    return redirect('blog:home')


@login_required
def user_page(request,id):
    current_user = User.objects.get(pk=id)
    return render(request, 'blog/user_page.html', {'user':current_user})


@login_required
def newsfeed(request):
    current_user = request.user
    follow_list = current_user.profile.following.all()
    post_list = list()
    for user in follow_list:
        for post in user.post_set.all():
            post_list.append(post)
    for i in range(0, len(post_list)-1):
        for j in range(i+1, len(post_list)):
            if post_list[i].date_published < post_list[j].date_published:
                post_list[i], post_list[j] = post_list[j], post_list[i]
    return render(request, 'blog/newsfeed.html', {'post_list': post_list})



@login_required
def list_of_users(request):
    current_user = request.user
    list_of_users = User.objects.exclude(pk = current_user.pk)
    return render(request, 'blog/list_of_users.html', {'list_of_users':list_of_users})


@login_required
def follow_user(request, username):
    current_user = request.user
    user = User.objects.get(username = username)
    current_userprofile = current_user.profile
    current_userprofile.following.add(user)
    return redirect('blog:following', user.id)


@login_required
def following(request,id):
    current_user = request.user
    userprofile = current_user.profile
    follow_list = userprofile.following.all()
    return render(request, 'blog/following.html', {'follow_list':follow_list})


@login_required
def unfollow(request, username):
    to_unfollow = User.objects.get(username=username)
    current_user = request.user
    userprofile = current_user.profile
    userprofile.following.remove(to_unfollow)
    return redirect('blog:newsfeed')


@login_required
def write_post(request):
    if request.method == 'GET':
        return render(request, 'blog/write_post.html')

    elif request.method == 'POST':
        current_user = request.user
        title = request.POST['title']
        text = request.POST['text']
        pub_date = datetime.datetime.now()
        post = Post(user = current_user, title = title, text = text)
        post.save()
        return redirect('blog:post_detail', post_pk = post.pk)


@login_required
def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comments = post.comments.all()
    return render(request, 'blog/post_detail.html', {'post':post, 'comments':comments,})



@login_required
def user_posts(request):
    current_user = request.user
    posts = current_user.post_set.all().order_by('date_published')
    return render(request, 'blog/user_posts.html', {'posts':posts})


@login_required
def delete_post(request, post_pk):
    user = request.user
    post = Post.objects.get(pk=post_pk)
    keep_record("post","delete",post_pk)
    post.delete()
    return user_page(request, user.id)


@login_required
def edit_profile(request):

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid:
            form.save()
            return redirect('blog:user_page', request.user.id)

    else:
        form=EditProfileForm(instance=request.user)
        return render(request, 'blog/edit_profile.html', {'form':form})

@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('blog:user_page', request.user.id)

    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, 'blog/password.html', {'form':form})



@login_required
def comment(request, post_pk):
    current_user = request.user
    post = Post.objects.get(pk = post_pk)
    comment_text = request.POST['comment']
    comment = Comment(user = current_user, post = post, comment = comment_text)
    comment.save()
    return post_detail(request, post_pk)

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <h1>My Site</h1>
  {% block content %}
  {% endblock %}
</body>
</html>

blog/templates/blog/edit.html
<html>

<head>
  <title>Edit Profile</title>
</head>

{% block content %}

<form method="post" action="{% url 'blog:edit' request.user.username %}">
  {% csrf_token %}

<br>
{% if messsages %}
  {% for message in messages %}
    {% if message.tags == "error" %}
      <p> {{message}} </p>
    {% endif %}
  {% endfor %}
{% endif %}
<br><br>

<div>
  <table>
    <tr>
      <td> Username</td>
      <td> {{user.username}}
    </tr>
    <tr>
      <td> First Name </td>
      <td><input type = "text" name="first_name" value="{{request.user.profile.first_name}}"/></td>
    </tr>
    <tr>
      <td> Last Name </td>
      <td><input type = "text" name="last_name" value="{{request.user.profile.last_name}}"/></td>
    </tr>
    <tr>
      <td><input type = "submit", value=submit></td>
    </tr>  
  </table>
</div>

{% endblock %}
</html>

blog/templates/blog/edit_profile.html
{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <br>
</div>

{% endblock %}

blog/templates/blog/following.html
<html>

<head>
  <title>Following</title>

  {% if request.user.is_authenticated %}

  <a href = {% url 'blog:newsfeed' %}><button style="color:green;width:150px;height:75px; font-size:25px">NewsFeed</button></a><br><br>
  <a href = {% url 'blog:user_page' user.id %}><button style="color:green;width:150px;height:75px; font-size:25px">Profile Page</button></a><br><br>
  <a href ={% url 'blog:logout_page' %}><button style="color:green;width:150px;height:75px; font-size:25px">Logout</button></a><br><br>

  <br><br><br><br><a style="font-size:30px;color:darkgreen"><b>Name</b> : {{user.first_name}} {{user.last_name}}</a><br>

  <a style="font-size:30px;color:darkgreen"><b>Username</b> : {{user.username}}</a>

  <br><h2 style="font-size:60px; color:blue">Following</h2>

  <body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
    {% if follow_list %}
      {% for user in follow_list %}
      <ul>
        <li><a href="{% url 'blog:user_page' user.id %}" style="font-size:40px;color:black">{{user.username}}</a></li>
        <a href="{% url 'blog:unfollow' user.username %}"><button> Unfollow</button></a></li>
      </ul>
    </body>
      {% endfor %}
    {% else %}
        <p> You are not following anyone! </p>
    {% endif %}
  {% else %}

    <h2>You are not logged in </h2>
    <br><h3>Login or signup first </h3>
    <a href = {% url 'blog:login_page' %}><button>Login</button></a>
    <a href = {% url 'blog:signup' %}><button>SignUp </button></a>

    {% endif %}

</head>

</html>

blog/templates/blog/home.html
<html>

<head>
  <title> BlogBook </title>
</head>

<body style = "background-color:#3b5998">

  <div>
    <h1 style="font-size:100px; color:white; font:Comic"><center> BlogBook </center></h1>
    <hr style="border-color:white">
    <br>
    <h2 style="font-size:50px; color:yellow"> BlogBook helps you connect with other bloggers all around the world</h2>
    <br>
    <p style="color:black; font-size:40px"> You can create a profile, upload posts, comment on other's posts and also follow other bloggers! </p>

    <h3 style="font-size:25px"> If you are a registered user, click on login, else first create an account by clicking on signup</h3>

  </div>

  <center><a href="signup"
  target="_blank"><button style="width:100px ; height:50px; color:white; background-color:darkblue">Sign Up</button></a></center>
  <br>
  <center><a href="login_page"
  target="_blank"><button style="width:100px ; height:50px; color:white; background-color:darkblue">Login</button></a></center>

</html>

blog/templates/blog/list_of_users.html
<html>

<head>
  <title>List Of Users</title>
</head>


<body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
  <h1 style="font-size:80px;color:black"><center>List Of Users</h1><br>
  {% if list_of_users %}
    <ul>
    {% for user in list_of_users %}
        <li>
        <a href = "{% url 'blog:user_page' user.id %}" style="font-size:40px;color:black">{{ user.username }}</a><br>
        <a href = "{% url 'blog:follow_user' user.username %}"><button style="width:75px;height:50px;color:green"> Follow </button></a><br><br><br>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <h2> Users not available! </h2>
  {% endif %}

</body>

</html>

blog/templates/blog/login_page.html
<html>

<head>
  <title>Login</title>
</head>

<body style = "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/futuretech1920x1234.jpg)">
  <center><h1 style="color:white; font-size:80px">Login</h1></center><br>

  {% if messages %}
    {% for message in messages %} <p class = "{{ message.tags }} " style="font-size:30px">{{ message }}</p> {% endfor %}
  {% endif %}


  <form action = "{% url 'blog:login_page' %}" method = "post">
  {% csrf_token %}
  <label for = 'username'><h2 style="font-size:40px; color:orange"> UserName: </h2></label>
    <input type = 'text', name = 'username'><br>
  <label for = 'password'><h2 style="font-size:40px; color:orange"> Password: </h2></label>
    <input type = 'password', name = 'password'><br><br>
  <input type = 'submit' , value = 'Submit'>
  </form>

  <h2 style="color:white"> Submit to create account. </h1>
    <br><br>
  <p><a href = {% url 'blog:signup' %}><button> Sign Up </button></a>


</body>
</html>

blog/templates/blog/newsfeed.html
<html>
<head>
  <title>News Feed</title>
</head>

<body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
  <h1 style="font-size:80px"><center> News Feed </h1>
  {% if post_list %}
    <ul>
      {% for post in post_list %}
      <li>
        <a href="{% url 'blog:post_detail' post.pk %}" style="font-size:40px;color:black">
        {{ post.title }}
      </a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2> No Posts are available. </h2>
  {% endif %}
  <br>
  <a href = "{% url 'blog:user_page' user.id %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> My Profile </button></a><br><br>
  <a href = "{% url 'blog:list_of_users' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> List Of Users </button></a><br><br>
  <a href = "{% url 'blog:following' user.id %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Follow List </button></a><br><br>
  <a href = "{% url 'blog:write_post' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Write Post </button></a><br><br>
  <a href = "{% url 'blog:user_posts' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> My Posts </button></a><br><br>
  <a href = "{% url 'blog:logout_page' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Logout </button></a><br><br>

</body>

</html>

blog/templates/blog/password.html
{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <br>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
<html>

{% load static %}
<head>
  <title>Post</title>
  <link rel="stylesheet" href="{% static 'post_detail.css' type="text/css" %}" />

<body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
  <h1 style="font-size:80px"><center>Welcome to post {{post.pk}}!</h1>
  {% if post %}
    <h2 style="font-size:40px; color:darkred"> Posted by: {{post.user.username}}</h2>
    <h2> Title of post is: {{ post.title }} </h2>
    <h2> Text: {{ post.text }} </h2>
    <br><br>
    <h2 style="font-size:40px"> Comments </h2>
    {% if comments %}
      <ul>
      {% for comment in comments %}
        <li style="font-size:25px"> {{comment.user}} : {{comment.comment}} </li>
      {% endfor %}
    </ul>
  {% endif %}
  <form action="{% url 'blog:comment' post.pk %}" method="post">
    {% csrf_token %}
    <label for = 'comment' style="font-size:40px"> Comment: </label>
      <input type = 'text' name='comment'><br>
    <input type = 'submit', value='Submit'>
  </form>

  {% else %}
    <h2> Post does not exist! </h2>
  {% endif %}

</body>
</head>

<a href="{% url 'blog:list_of_users' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> List of users </button></a><br>
<a href="{% url 'blog:following' user.id %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Follow List</button></a><br>
<a href="{% url 'blog:write_post' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Write a New Post </button></a><br>
<a href="{% url 'blog:user_page' user.id %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> My Profile </button></a><br>
<a href="{% url 'blog:user_posts' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> My Posts </button></a><br>
<a href="{% url 'blog:logout_page' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Logout </button></a><br>


</html>

blog/templates/blog/signup.html
<head>
<title>SignUp</title>
</head>
<body style="background-color:#3b5998">
{% block content %}
  <h2 style="font-size:60px; color:black"><center>Sign up</h2>
  <form method="post" style="color:yellow;font-size:30px">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}
</body

blog/templates/blog/user_page.html
<html>

<head>
  <title>Profile page</title>
</head>
{% load static %}
<body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)" >
  <h1 style="color:black;font-size:80px"><center>Profile Page</h1><br>

  {% if messsages %}
    {% for message in messages%}
      <p class = "{{ message.tags }}">{{ message }}</p>
    {% endfor %}
  {% endif %}

  {% if user %}
    <ul>
      <li style="font-size:40px; color:blue">First Name: {{user.first_name}}</li>
      <li style="font-size:40px; color:blue">Last Name: {{user.last_name}}</li>
      <li style="font-size:40px; color:blue">User Name: {{user.username}}</li>
      <a href = "{%url 'blog:edit_profile' %}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Edit Profile </button></a>

    </ul>
  {% else %}
    <h2> Error </h2>
  {% endif %}


  <br>
  <a href = "{% url 'blog:list_of_users' %}"><button style="color:green;width:150px;height:75px; font-size:25px"> List Of Users </button></a><br><br><br>
  <a href = "{% url 'blog:following' user.id %}"><button style="color:green;width:150px;height:90px; font-size:25px"> List Of Users I am following </button></a><br><br><br>
  <a href = "{% url 'blog:write_post' %}"><button style="color:green;width:150px;height:90px; font-size:25px"> Write a Post </button></a><br><br><br>
  <a href = "{% url 'blog:newsfeed' %}"><button style="color:green;width:150px;height:90px; font-size:25px">  NewsFeed </button></a><br><br><br>
  <a href = "{% url 'blog:user_posts' %}"><button style="color:green;width:150px;height:90px; font-size:25px"> My Posts </button></a><br><br><br>
  <a href = "{% url 'blog:logout_page' %}"><button style="color:green;width:150px;height:90px; font-size:25px"> Logout </button></a><br><br><br>
</body>

</html>

blog/templates/blog/user_posts.html
<html>

<head>
  <title>My Posts</title>

  <body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
    <h1 style="font-size:80px"><center>My Posts</h1>
    {% if posts %}
      <ul>
        {% for post in posts %}
          <li>
            <a href = "{% url 'blog:post_detail' post.pk %}" style="font-size:40px; color:black">{{ post.title }}</a><br>
            <a href = "{% url 'blog:delete_post' post.pk %}" style="font-size:20px; color:red"> Delete </a><br><br>
          </li>
        {% endfor %}
      </ul>

    {% else %}
      <h2> You have not posted anything </h2>
    {% endif %}
    <a href = "{% url 'blog:write_post'%}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Write a new post </button></a><br><br>
    <a href = "{% url 'blog:newsfeed'%}"><button style="width:100px; height:75px; color:darkgreen;background-color:lightblue"> Return back to NewsFeed </button></a>

</body>



</html>

blog/templates/blog/write_post.html
<html>

<head>
  <title>Write New Post </title>
</head>

<body style= "background: url(http://blog.hostbaby.com/wp-content/uploads/2013/07/antiquepaper_1920x1234.jpg)">
  <h1 style="font-size:80px"><center>Write New Post</h1><br>
  <form action="{% url 'blog:write_post' %}" method = "post">
    {% csrf_token %}
  <label for = "title"><h2 style="font-size:40px; color:blue">Title: </h2><br>
    <input type="text" name="title" style="height:50px;width:500px"><br>
  <label for = "text"><h2 style="font-size:40px; color:blue">Text: </h2><br>
    <input type="text" name="text" style="height:200px;width:1100"><br><br>
  <input type = "submit", value="Submit">
  </form>
  

</body>
</html>